language: java
jdk:
  - oraclejdk8
  
sudo: required

script: ./mvnw clean package

services:
  - docker

before_install:
  - docker pull neo4j
  - docker run -d --name neo4j --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=neo4j/test neo4j:3.0
  - docker ps -a
  
after_success:
  - ./mvnw clean verify coveralls:report -P integration-tests,coveralls