language: java
jdk:
- oraclejdk8
sudo: required
addons:
  sonarqube:
    token:
      secure: VFCEIp3tO4KChdAF+CkNk0+UXgoPDU04ivnCENjZejcXJVDDfsAmqmUfVkf8a0xox6JcCEV93NOcJRe93KHfgQeA5L3RP6ODF4f8cX4WRZYv0oFvgbaelxCT26JqvKEyXgSt0BblPYyk4lkCm3L/rV+nT1Q7DuGD+2q8AZ/IR3aRUeQHm4lcQKDbsOFhCRmnFfPq6KbQUFn4U3DUt45vjGTyEi51xEIKFyGhyHM9HhxDlrKv7pXXXOWL+5EIiOrYCpHqF5oqEeWkP47jqXUcu9aGAfrzBTdsAmumtFPqcyflQ/j6FkqgYStSQG8bpKBME5WKcrNzekNmMaFqd9a+DoPiUGwlwUzwgSxjQXOe+lZgD1O7248BHIbrfQyWnAHTNUVzGake9yqVXg8qM6bzBfnoZzaJPs1L+BcoDx0NB5CV1Q+GJeAe95gXFLEgpKAv8Q8tUGC8ripLMWRm5tKPF7S8xXy91a8ZoVYFAps65KMr6GPFdaceH/455sXLz1fY1Oy5oWOK+7tGV4RX7anuYbDVJwzMCEQzP6EjzStE2GN1JMjiF/DgSSyzHcuR1VQsOGtJDkJV7aBgzY3tDSJ3e1UCSklDfLI0x1bwymAEgzLtsiAk2bKM68CG4ayEvupo4q21Z/thurOjjn49aakS6yMaLuOei7lIxPzfIrqnrIY=
script: ./mvnw clean package
services:
- docker
before_install:
- docker pull neo4j
- docker run -d --name neo4j --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=neo4j/test
  neo4j:3.0
- docker ps -a
after_success:
- ./mvnw clean verify coveralls:report -P integration-tests,coveralls
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
