language: java
jdk:
- oraclejdk8

sudo: required

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

addons:
  sonarqube:
    token:
      secure: $SONARQUBE_AUTH_TOKEN

script: ./mvnw clean package

services:
- docker

before_install:
- docker run -d --name neo4j --publish=7474:7474 --publish=7687:7687 --env=NEO4J_AUTH=neo4j/password
  neo4j:3.2
- docker ps -a

after_success:
- ./mvnw clean verify coveralls:report -P integration-tests,coveralls
- ./mvnw clean verify org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -P integration-tests

deploy:
  provider: heroku
  app: lift-service
  api_key:
    secure: $HEROKU_AUTH_TOKEN
